# Generated by Django 4.2.2 on 2023-06-21 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_album_apod_satellite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='date',
        ),
        migrations.RemoveField(
            model_name='apod',
            name='description',
        ),
        migrations.RemoveField(
            model_name='apod',
            name='image',
        ),
        migrations.RemoveField(
            model_name='apod',
            name='name',
        ),
        migrations.AddField(
            model_name='apod',
            name='title',
            field=models.CharField(default='APOD', max_length=100),
        ),
        migrations.AddField(
            model_name='apod',
            name='url',
            field=models.URLField(default=''),
        ),
        migrations.DeleteModel(
            name='Constellation',
        ),
    ]
