# Generated by Django 4.2.2 on 2023-06-22 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_remove_album_date_remove_apod_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='apod_photos',
            field=models.ManyToManyField(to='main_app.apod'),
        ),
    ]
