# Generated by Django 4.2.2 on 2023-06-22 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_album_apod_photos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='apod',
            options={'ordering': ['title']},
        ),
        migrations.AddField(
            model_name='album',
            name='description',
            field=models.TextField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
