# Generated by Django 4.2.2 on 2023-06-23 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_album_options_alter_apod_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apod',
            name='explanation',
            field=models.TextField(default='', max_length=3000),
            preserve_default=False,
        ),
    ]
