# Generated by Django 4.2.2 on 2023-06-25 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0007_album_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='apod_photos',
        ),
        migrations.CreateModel(
            name='SavedApod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('apod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.apod')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='saved_apods',
            field=models.ManyToManyField(to='main_app.savedapod'),
        ),
        migrations.AddField(
            model_name='apod',
            name='saved_by',
            field=models.ManyToManyField(through='main_app.SavedApod', to=settings.AUTH_USER_MODEL),
        ),
    ]
