# Generated by Django 4.2.2 on 2023-06-25 18:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0008_remove_album_apod_photos_savedapod_album_saved_apods_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='saved_apods',
        ),
        migrations.RemoveField(
            model_name='apod',
            name='saved_by',
        ),
        migrations.AddField(
            model_name='album',
            name='apod_photos',
            field=models.ManyToManyField(to='main_app.apod'),
        ),
        migrations.AddField(
            model_name='apod',
            name='users',
            field=models.ManyToManyField(related_name='apods', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='SavedApod',
        ),
    ]
